#!/usr/bin/env python3
"""Generate native/blender_gp/lineart/project_grease_lineart_cpu.cc from the pinned Blender 3.6.23
gpencil_modifiers_legacy/intern/lineart/lineart_cpu.cc (Line Art batch 2).

The pinned file is emitted in its original order as BEGIN/END VERBATIM regions (checked by
tools/verify_blender_verbatim.py). Only the items that read Blender's Mesh / Object / Depsgraph /
Collection / Material data or write GP output are swapped: each REPLACED item is substituted by the
section of the same name in native/blender_gp/lineart/lineart_scene_lite_replacements.cc (Scene-lite
versions, written to follow the original line by line), and each DROPPED item is left out (GP
output is batch 3). The include block is replaced by the Project Grease shim includes.

usage: python3 tools/gen_lineart_lite.py [--check]
  --check  fail when the committed output differs from what would be generated
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REL = "source/blender/gpencil_modifiers_legacy/intern/lineart/lineart_cpu.cc"
SRC = ROOT / "third_party" / "blender" / REL
REPL = ROOT / "native/blender_gp/lineart/lineart_scene_lite_replacements.cc"
OUT = ROOT / "native/blender_gp/lineart/project_grease_lineart_cpu.cc"

# Items (by the name they define) that read Mesh / Object / Depsgraph / Collection / Material data.
REPLACED = [
    "EdgeFeatData", "lineart_identify_mlooptri_feature_edges", "TriData", "lineart_load_tri_task",
    "EdgeNeighborData", "lineart_edge_neighbor_init_task", "lineart_build_edge_neighbor",
    "lineart_geometry_object_load", "lineart_intersection_mask_check",
    "lineart_intersection_priority_check", "lineart_usage_check", "lineart_geometry_check_visible",
    "lineart_object_load_single_instance", "lineart_main_load_geometries",
    "lineart_create_render_buffer", "MOD_lineart_compute_feature_lines", "lineart_gpencil_generate",
]
# Modifier-data plumbing (the GP modifier itself is not used: lineart_gpencil_generate is replaced
# by a version that writes Project Grease strokes).
DROPPED = ["MOD_lineart_destroy_render_data", "MOD_lineart_gpencil_generate"]

HEADER = """/* SPDX-License-Identifier: GPL-2.0-or-later
 *
 * GENERATED by tools/gen_lineart_lite.py from the pinned Blender 3.6.23
 * {rel}. Do not edit: change the generator or
 * lineart_scene_lite_replacements.cc and regenerate.
 *
 * Every region marked BEGIN/END VERBATIM is the pinned source byte for byte. The items that read
 * Mesh / Object / Depsgraph / Collection / Material data are Scene-lite replacements (see the
 * replacements file); GP stroke output is not included yet.
 */

#include "lineart_lite_shim.h"
"""


def item_spans(lines):
    """(start, end, name) of every top-level function or struct; end is inclusive."""
    spans = []
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        m_struct = re.match(r"^struct (\w+) \{", line)
        m_func = None
        if not m_struct and re.match(r"^[A-Za-z]", line) and "(" in line and not line.rstrip().endswith(";"):
            m_func = re.search(r"(\w+)\s*\(", line)
        if not (m_struct or m_func):
            i += 1
            continue
        name = (m_struct or m_func).group(1)
        depth = 0
        seen_open = False
        j = i
        while j < n:
            depth += lines[j].count("{") - lines[j].count("}")
            if "{" in lines[j]:
                seen_open = True
            if seen_open and depth == 0:
                break
            if not seen_open and lines[j].rstrip().endswith(";"):
                break  # a declaration, not a definition
            j += 1
        if seen_open:
            spans.append((i, j, name))
        i = j + 1
    return spans


def replacement_sections(text):
    sections = {}
    for m in re.finditer(r"^//@@ (\w+)\n(.*?)(?=^//@@ |\Z)", text, re.S | re.M):
        sections[m.group(1)] = m.group(2).rstrip("\n")
    return sections


def generate():
    lines = SRC.read_text(encoding="utf-8").split("\n")
    sections = replacement_sections(REPL.read_text(encoding="utf-8"))
    missing = [n for n in REPLACED if n not in sections]
    if missing:
        raise SystemExit("replacement sections missing: " + ", ".join(missing))
    # Skip the original include block: everything up to the last top-level #include.
    first = max(i for i, l in enumerate(lines[:80]) if l.startswith("#include")) + 1
    spans = [s for s in item_spans(lines) if s[0] >= first]
    names = {s[2] for s in spans}
    for name in REPLACED + DROPPED:
        if name not in names:
            raise SystemExit(f"{name} not found in {REL}")
    out = [HEADER.format(rel=REL)]
    if "prelude" in sections:
        out.append(sections["prelude"])
    cursor = first
    verbatim = []

    def flush():
        # Trim blank lines at the edges so regions stay contiguous blocks of the original.
        while verbatim and not verbatim[0].strip():
            verbatim.pop(0)
        while verbatim and not verbatim[-1].strip():
            verbatim.pop()
        if verbatim:
            out.append(f"/* BEGIN VERBATIM {REL} */\n" + "\n".join(verbatim) + "\n/* END VERBATIM */")
        verbatim.clear()

    for start, end, name in spans:
        if name not in REPLACED and name not in DROPPED:
            continue
        verbatim.extend(lines[cursor:start])
        flush()
        if name in REPLACED:
            out.append(f"/* Scene-lite replacement for {name} (lineart_scene_lite_replacements.cc) */\n"
                       + sections[name])
        else:
            out.append(f"/* {name}: not included (Blender GP modifier plumbing; see lineart_gpencil_generate). */")
        cursor = end + 1
    verbatim.extend(lines[cursor:])
    flush()
    if "epilogue" in sections:
        out.append(sections["epilogue"])
    return "\n\n".join(out) + "\n"


def main():
    text = generate()
    if "--check" in sys.argv:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run tools/gen_lineart_lite.py", file=sys.stderr)
            return 1
        print("generated Line Art source is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print("wrote", OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
